# Generated by Django 3.0.8 on 2020-07-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='elevator',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
