# Generated by Django 3.0.8 on 2020-07-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0002_auto_20200723_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='lot_count',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
