# Generated by Django 3.0.8 on 2020-07-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0004_auto_20200723_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
