# Generated by Django 3.0.8 on 2020-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0005_auto_20200723_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='heating_mode',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estateadverts',
            name='parking_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estateadverts',
            name='water_heating_mode',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
