# Generated by Django 3.0.8 on 2020-07-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0006_auto_20200723_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='heating_mode',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='estateadverts',
            name='parking_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='estateadverts',
            name='water_heating_mode',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
