# Generated by Django 3.0.8 on 2020-07-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0007_auto_20200723_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='heating_mode',
            field=models.CharField(blank=True, choices=[('COLLECTIVE', 'Collective'), ('INDIVIDUAL', 'Individual')], db_index=True, max_length=12, null=True),
        ),
    ]
