# Generated by Django 3.0.8 on 2020-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleur_corpo', '0008_auto_20200723_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadverts',
            name='condominium_expenses',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
